var namespace_spectra_logic_1_1_spectra_rio_broker_client_1_1_runtime =
[
    [ "ServerCertificateValidation", "class_spectra_logic_1_1_spectra_rio_broker_client_1_1_runtime_1_1_server_certificate_validation.html", "class_spectra_logic_1_1_spectra_rio_broker_client_1_1_runtime_1_1_server_certificate_validation" ]
];