var namespace_spectra_logic_1_1_spectra_rio_broker_client_1_1_calls_1_1_devices =
[
    [ "CreateSpectraDeviceRequest", "class_spectra_logic_1_1_spectra_rio_broker_client_1_1_calls_1_1_devices_1_1_create_spectra_device_request.html", "class_spectra_logic_1_1_spectra_rio_broker_client_1_1_calls_1_1_devices_1_1_create_spectra_device_request" ],
    [ "DeleteSpectraDeviceRequest", "class_spectra_logic_1_1_spectra_rio_broker_client_1_1_calls_1_1_devices_1_1_delete_spectra_device_request.html", "class_spectra_logic_1_1_spectra_rio_broker_client_1_1_calls_1_1_devices_1_1_delete_spectra_device_request" ],
    [ "GetSpectraDeviceRequest", "class_spectra_logic_1_1_spectra_rio_broker_client_1_1_calls_1_1_devices_1_1_get_spectra_device_request.html", "class_spectra_logic_1_1_spectra_rio_broker_client_1_1_calls_1_1_devices_1_1_get_spectra_device_request" ],
    [ "GetSpectraDevicesRequest", "class_spectra_logic_1_1_spectra_rio_broker_client_1_1_calls_1_1_devices_1_1_get_spectra_devices_request.html", "class_spectra_logic_1_1_spectra_rio_broker_client_1_1_calls_1_1_devices_1_1_get_spectra_devices_request" ]
];